// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prog3.Models
{
    public partial class Compra
    {
        public Compra()
        {
            DetalleCompra = new HashSet<DetalleCompra>();
        }

        public int IdCompra { get; set; }
        public int IdProveedor { get; set; }
        public DateTime? Fecha { get; set; }
        public double? TotalCompra { get; set; }

        public virtual Proveedor IdProveedorNavigation { get; set; }
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
    }
}