// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prog3.Models
{
    public partial class Direccion
    {
        public int IdDireccion { get; set; }
        public int IdPersona { get; set; }
        public string Provincia { get; set; }
        public string Ciudad { get; set; }
        public string Calle { get; set; }
        public string NumeroCalle { get; set; }

        public virtual Persona IdPersonaNavigation { get; set; }
    }
}