// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prog3.Models
{
    public partial class Persona
    {
        public Persona()
        {
            Cliente = new HashSet<Cliente>();
            Direccion = new HashSet<Direccion>();
            Proveedor = new HashSet<Proveedor>();
        }

        public int IdPersona { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string RazonSocial { get; set; }

        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Direccion> Direccion { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
    }
}